// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TatterFitness.Dal.Entities
{
    public partial class ExerciseEntity
    {
        public ExerciseEntity()
        {
            RoutineExercises = new HashSet<RoutineExerciseEntity>();
            WorkoutExercises = new HashSet<WorkoutExerciseEntity>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int ExerciseTypeId { get; set; }
        public bool IsActive { get; set; }

        public virtual ExerciseTypeEntity ExerciseType { get; set; } = null!;
        public virtual ICollection<RoutineExerciseEntity> RoutineExercises { get; set; }
        public virtual ICollection<WorkoutExerciseEntity> WorkoutExercises { get; set; }
    }
}