// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TatterFitness.Dal.Entities
{
    public partial class RoutineExerciseEntity
    {
        public int RoutineId { get; set; }
        public int ExerciseId { get; set; }
        public int Id { get; set; }

        public virtual ExerciseEntity Exercise { get; set; } = null!;
        public virtual RoutineEntity Routine { get; set; } = null!;
    }
}