// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TatterFitness.Dal.Entities
{
    public partial class UserEntity
    {
        public UserEntity()
        {
            BodyMetricRecords = new HashSet<BodyMetricRecordEntity>();
            Routines = new HashSet<RoutineEntity>();
            Workouts = new HashSet<WorkoutEntity>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;

        public virtual ICollection<BodyMetricRecordEntity> BodyMetricRecords { get; set; }
        public virtual ICollection<RoutineEntity> Routines { get; set; }
        public virtual ICollection<WorkoutEntity> Workouts { get; set; }
    }
}