// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TatterFitness.Dal.Entities
{
    public partial class VideoEntity
    {
        public int Id { get; set; }
        public byte[] VideoData { get; set; } = null!;
        public byte[] Hash { get; set; } = null!;
        public int WorkoutExerciseId { get; set; }

        public virtual WorkoutExerciseEntity WorkoutExercise { get; set; } = null!;
    }
}