// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TatterFitness.Dal.Entities
{
    public partial class WorkoutExerciseModifierEntity
    {
        public int WorkoutExerciseId { get; set; }
        public int ExerciseModifierId { get; set; }
        public int Id { get; set; }

        public virtual ExerciseModifierEntity ExerciseModifier { get; set; } = null!;
        public virtual WorkoutExerciseEntity WorkoutExercise { get; set; } = null!;
    }
}
