// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using TatterFitness.Dal.Persistance;
using Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal;
using Microsoft.Extensions.Configuration;
using TatterFitness.Dal.Persistance.Configurations;

namespace TatterFitness.Dal.Persistence
{
    public partial class TatterDb : DbContext
    {
        public TatterDb()
        {
        }

        public TatterDb(DbContextOptions<TatterDb> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
{
            modelBuilder.ApplyConfiguration(new BodyMetricRecordConfiguration());
            modelBuilder.ApplyConfiguration(new ExerciseConfiguration());
            modelBuilder.ApplyConfiguration(new ExerciseModifierConfiguration());
            modelBuilder.ApplyConfiguration(new ExerciseTypeConfiguration());
            modelBuilder.ApplyConfiguration(new RoutineConfiguration());
            modelBuilder.ApplyConfiguration(new RoutineExerciseConfiguration());
            modelBuilder.ApplyConfiguration(new UserConfiguration());
            modelBuilder.ApplyConfiguration(new VideoConfiguration());
            modelBuilder.ApplyConfiguration(new WorkoutConfiguration());
            modelBuilder.ApplyConfiguration(new WorkoutExerciseConfiguration());
            modelBuilder.ApplyConfiguration(new WorkoutExerciseModifierConfiguration());
            modelBuilder.ApplyConfiguration(new WorkoutExerciseSetConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
