// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TatterFitness.Models
{
    public partial class BodyMetricRecord
    {
        public int Id { get; set; }
        public double? Weight { get; set; }
        public double? FatPercentage { get; set; }
        public double? Waist { get; set; }
        public double? Chest { get; set; }
        public double? Upperarms { get; set; }
        public double? Forearms { get; set; }
        public double? Shoulders { get; set; }
        public double? Hips { get; set; }
        public double? Thighs { get; set; }
        public double? Calves { get; set; }
        public double? Neck { get; set; }
        public int? Height { get; set; }
        public DateTime Date { get; set; }
        public int UserId { get; set; }
    }
}