// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TatterFitness.Dal.Entities;
using TatterFitness.Dal.Persistance;

#nullable disable

namespace TatterFitness.Dal.Persistance.Configurations
{
    public partial class RoutineExerciseConfiguration : IEntityTypeConfiguration<RoutineExerciseEntity>
    {
        public void Configure(EntityTypeBuilder<RoutineExerciseEntity> entity)
        {
            entity.ToTable("RoutineExercises");
            entity.HasOne(d => d.Exercise)
                .WithMany(p => p.RoutineExercises)
                .HasForeignKey(d => d.ExerciseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoutineExercises_Exercises");

            entity.HasOne(d => d.Routine)
                .WithMany(p => p.RoutineExercises)
                .HasForeignKey(d => d.RoutineId)
                .HasConstraintName("FK_RoutineExercises_Routines");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoutineExerciseEntity> entity);
    }
}
