// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TatterFitness.Dal.Entities;
using TatterFitness.Dal.Persistance;

#nullable disable

namespace TatterFitness.Dal.Persistance.Configurations
{
    public partial class WorkoutExerciseConfiguration : IEntityTypeConfiguration<WorkoutExerciseEntity>
    {
        public void Configure(EntityTypeBuilder<WorkoutExerciseEntity> entity)
        {
            entity.ToTable("WorkoutExercises");
            entity.HasOne(d => d.Workout)
                .WithMany(p => p.WorkoutExercises)
                .HasForeignKey(d => d.WorkoutId)
                .HasConstraintName("FK_WorkoutExercises_Workouts");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkoutExerciseEntity> entity);
    }
}
