// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TatterFitness.Dal.Entities;
using TatterFitness.Dal.Persistance;

#nullable disable

namespace TatterFitness.Dal.Persistance.Configurations
{
    public partial class WorkoutExerciseSetConfiguration : IEntityTypeConfiguration<WorkoutExerciseSetEntity>
    {
        public void Configure(EntityTypeBuilder<WorkoutExerciseSetEntity> entity)
        {
            entity.ToTable("WorkoutExerciseSets");
            entity.HasOne(d => d.WorkoutExercise)
                .WithMany(p => p.WorkoutExerciseSets)
                .HasForeignKey(d => d.WorkoutExerciseId)
                .HasConstraintName("FK_WorkoutExerciseSets_WorkoutExercises");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkoutExerciseSetEntity> entity);
    }
}
