// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TatterFitness.Dal.Entities;
using TatterFitness.Dal.Persistance;

#nullable disable

namespace TatterFitness.Dal.Persistance.Configurations
{
    public partial class WorkoutExerciseModifierConfiguration : IEntityTypeConfiguration<WorkoutExerciseModifierEntity>
    {
        public void Configure(EntityTypeBuilder<WorkoutExerciseModifierEntity> entity)
        {
            entity.ToTable("WorkoutExerciseModifiers");
            entity.HasOne(d => d.ExerciseModifier)
                .WithMany(p => p.WorkoutExerciseModifiers)
                .HasForeignKey(d => d.ExerciseModifierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkoutExerciseModifiers_ExerciseModifiers");

            entity.HasOne(d => d.WorkoutExercise)
                .WithMany(p => p.WorkoutExerciseModifiers)
                .HasForeignKey(d => d.WorkoutExerciseId)
                .HasConstraintName("FK_WorkoutExerciseModifiers_WorkoutExercises");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkoutExerciseModifierEntity> entity);
    }
}
